<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cls.proto

namespace Cls\Protobuf\GPBMetadata;

class Cls
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88020a09636c732e70726f746f1203636c73225e0a034c6f67120c0a04" .
            "74696d6518012001280312220a08636f6e74656e747318022003280b3210" .
            "2e636c732e4c6f672e436f6e74656e741a250a07436f6e74656e74120b0a" .
            "036b6579180120012809120d0a0576616c756518022001280922590a084c" .
            "6f6747726f757012160a046c6f677318012003280b32082e636c732e4c6f" .
            "6712130a0b636f6e74657874466c6f7718022001280912100a0866696c65" .
            "6e616d65180320012809120e0a06736f7572636518042001280922330a0c" .
            "4c6f6747726f75704c69737412230a0c6c6f6747726f75704c6973741801" .
            "2003280b320d2e636c732e4c6f6747726f7570620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

